server {
    listen 80;
    server_name _;

    root /var/www/getreleased;
    index index.html;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri.html $uri/ /404.html;
    }

    location /data/ {
        add_header Cache-Control "no-cache";
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /_next/static/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
